version: "3"
services:
  php:
    container_name: {{ cookiecutter.project_slug }}_php
    build: ./docker/php/
    volumes:
      - ./webroot/:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d/
  webserver:
    container_name: {{ cookiecutter.project_slug }}_webserver
    image: nginx:latest
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webroot/:/var/www/html
    links:
      - php
      - mysql
  mysql:
    container_name: {{ cookiecutter.project_slug }}_mysql
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "wordpress"
    ports:
      - 3306:3306
    volumes:
      - db_data-{{ cookiecutter.project_slug }}:/var/lib/mysql
  phpmyadmin:
      container_name: {{ cookiecutter.project_slug }}_phpmyadmin
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql
      ports:
        - 8001:80
      environment:
        MYSQL_ROOT_PASSOWRD: wordpress
        UPLOAD_LIMIT: 300M
        PMA_HOST: localhost
        PMA_HOST: mysql
        PMA_USER: admin
        PMA_PASSWORD: admin

volumes:
  db_data-{{ cookiecutter.project_slug }}: {}
